// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMessageProto.proto

package com.jjpicture.mvvmstar.im_common.protocol;

public final class ChatMessageProto {
  private ChatMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMessageProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string msgId = 1;</code>
     */
    boolean hasMsgId();
    /**
     * <code>required string msgId = 1;</code>
     */
    String getMsgId();
    /**
     * <code>required string msgId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <code>required int64 fromId = 2;</code>
     */
    boolean hasFromId();
    /**
     * <code>required int64 fromId = 2;</code>
     */
    long getFromId();

    /**
     * <code>required int64 toId = 3;</code>
     */
    boolean hasToId();
    /**
     * <code>required int64 toId = 3;</code>
     */
    long getToId();

    /**
     * <pre>
     * 聊天类型：单聊、群聊、语音通话
     * </pre>
     *
     * <code>required int32 chatType = 4;</code>
     */
    boolean hasChatType();
    /**
     * <pre>
     * 聊天类型：单聊、群聊、语音通话
     * </pre>
     *
     * <code>required int32 chatType = 4;</code>
     */
    int getChatType();

    /**
     * <code>required int64 timestamp = 5;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 5;</code>
     */
    long getTimestamp();

    /**
     * <code>required int32 level = 6;</code>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 6;</code>
     */
    int getLevel();

    /**
     * <pre>
     * 消息类型：文本、文件、图片等
     * </pre>
     *
     * <code>required int32 msgType = 7;</code>
     */
    boolean hasMsgType();
    /**
     * <pre>
     * 消息类型：文本、文件、图片等
     * </pre>
     *
     * <code>required int32 msgType = 7;</code>
     */
    int getMsgType();

    /**
     * <code>required bytes msgBody = 8;</code>
     */
    boolean hasMsgBody();
    /**
     * <code>required bytes msgBody = 8;</code>
     */
    com.google.protobuf.ByteString getMsgBody();

    /**
     * <pre>
     * 扩展
     * </pre>
     *
     * <code>required string ext = 9;</code>
     */
    boolean hasExt();
    /**
     * <pre>
     * 扩展
     * </pre>
     *
     * <code>required string ext = 9;</code>
     */
    String getExt();
    /**
     * <pre>
     * 扩展
     * </pre>
     *
     * <code>required string ext = 9;</code>
     */
    com.google.protobuf.ByteString
        getExtBytes();
  }
  /**
   * Protobuf type {@code com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProtocol}
   */
  public  static final class ChatMessageProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProtocol)
      ChatMessageProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatMessageProtocol.newBuilder() to construct.
    private ChatMessageProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMessageProtocol() {
      msgId_ = "";
      fromId_ = 0L;
      toId_ = 0L;
      chatType_ = 0;
      timestamp_ = 0L;
      level_ = 0;
      msgType_ = 0;
      msgBody_ = com.google.protobuf.ByteString.EMPTY;
      ext_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMessageProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              msgId_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fromId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              toId_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              chatType_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timestamp_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              level_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              msgType_ = input.readInt32();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              msgBody_ = input.readBytes();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              ext_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.internal_static_com_star_common_protocol_ChatMessageProtocol_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.internal_static_com_star_common_protocol_ChatMessageProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol.class, com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol.Builder.class);
    }

    private int bitField0_;
    public static final int MSGID_FIELD_NUMBER = 1;
    private volatile Object msgId_;
    /**
     * <code>required string msgId = 1;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string msgId = 1;</code>
     */
    public String getMsgId() {
      Object ref = msgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msgId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMID_FIELD_NUMBER = 2;
    private long fromId_;
    /**
     * <code>required int64 fromId = 2;</code>
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 fromId = 2;</code>
     */
    public long getFromId() {
      return fromId_;
    }

    public static final int TOID_FIELD_NUMBER = 3;
    private long toId_;
    /**
     * <code>required int64 toId = 3;</code>
     */
    public boolean hasToId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 toId = 3;</code>
     */
    public long getToId() {
      return toId_;
    }

    public static final int CHATTYPE_FIELD_NUMBER = 4;
    private int chatType_;
    /**
     * <pre>
     * 聊天类型：单聊、群聊、语音通话
     * </pre>
     *
     * <code>required int32 chatType = 4;</code>
     */
    public boolean hasChatType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * 聊天类型：单聊、群聊、语音通话
     * </pre>
     *
     * <code>required int32 chatType = 4;</code>
     */
    public int getChatType() {
      return chatType_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 5;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 timestamp = 5;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int LEVEL_FIELD_NUMBER = 6;
    private int level_;
    /**
     * <code>required int32 level = 6;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 level = 6;</code>
     */
    public int getLevel() {
      return level_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 7;
    private int msgType_;
    /**
     * <pre>
     * 消息类型：文本、文件、图片等
     * </pre>
     *
     * <code>required int32 msgType = 7;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * 消息类型：文本、文件、图片等
     * </pre>
     *
     * <code>required int32 msgType = 7;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int MSGBODY_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString msgBody_;
    /**
     * <code>required bytes msgBody = 8;</code>
     */
    public boolean hasMsgBody() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required bytes msgBody = 8;</code>
     */
    public com.google.protobuf.ByteString getMsgBody() {
      return msgBody_;
    }

    public static final int EXT_FIELD_NUMBER = 9;
    private volatile Object ext_;
    /**
     * <pre>
     * 扩展
     * </pre>
     *
     * <code>required string ext = 9;</code>
     */
    public boolean hasExt() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <pre>
     * 扩展
     * </pre>
     *
     * <code>required string ext = 9;</code>
     */
    public String getExt() {
      Object ref = ext_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ext_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 扩展
     * </pre>
     *
     * <code>required string ext = 9;</code>
     */
    public com.google.protobuf.ByteString
        getExtBytes() {
      Object ref = ext_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChatType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, fromId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, toId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, chatType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, timestamp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, level_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, msgType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, msgBody_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, ext_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, fromId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, toId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, chatType_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timestamp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, level_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, msgType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, msgBody_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, ext_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol)) {
        return super.equals(obj);
      }
      com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol other = (com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol) obj;

      boolean result = true;
      result = result && (hasMsgId() == other.hasMsgId());
      if (hasMsgId()) {
        result = result && getMsgId()
            .equals(other.getMsgId());
      }
      result = result && (hasFromId() == other.hasFromId());
      if (hasFromId()) {
        result = result && (getFromId()
            == other.getFromId());
      }
      result = result && (hasToId() == other.hasToId());
      if (hasToId()) {
        result = result && (getToId()
            == other.getToId());
      }
      result = result && (hasChatType() == other.hasChatType());
      if (hasChatType()) {
        result = result && (getChatType()
            == other.getChatType());
      }
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && (hasLevel() == other.hasLevel());
      if (hasLevel()) {
        result = result && (getLevel()
            == other.getLevel());
      }
      result = result && (hasMsgType() == other.hasMsgType());
      if (hasMsgType()) {
        result = result && (getMsgType()
            == other.getMsgType());
      }
      result = result && (hasMsgBody() == other.hasMsgBody());
      if (hasMsgBody()) {
        result = result && getMsgBody()
            .equals(other.getMsgBody());
      }
      result = result && (hasExt() == other.hasExt());
      if (hasExt()) {
        result = result && getExt()
            .equals(other.getExt());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgId()) {
        hash = (37 * hash) + MSGID_FIELD_NUMBER;
        hash = (53 * hash) + getMsgId().hashCode();
      }
      if (hasFromId()) {
        hash = (37 * hash) + FROMID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFromId());
      }
      if (hasToId()) {
        hash = (37 * hash) + TOID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getToId());
      }
      if (hasChatType()) {
        hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getChatType();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasLevel()) {
        hash = (37 * hash) + LEVEL_FIELD_NUMBER;
        hash = (53 * hash) + getLevel();
      }
      if (hasMsgType()) {
        hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMsgType();
      }
      if (hasMsgBody()) {
        hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
        hash = (53 * hash) + getMsgBody().hashCode();
      }
      if (hasExt()) {
        hash = (37 * hash) + EXT_FIELD_NUMBER;
        hash = (53 * hash) + getExt().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProtocol)
        com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.internal_static_com_star_common_protocol_ChatMessageProtocol_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.internal_static_com_star_common_protocol_ChatMessageProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol.class, com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol.Builder.class);
      }

      // Construct using com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        fromId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        toId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        chatType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        msgBody_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        ext_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.internal_static_com_star_common_protocol_ChatMessageProtocol_descriptor;
      }

      public com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol getDefaultInstanceForType() {
        return com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol.getDefaultInstance();
      }

      public com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol build() {
        com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol buildPartial() {
        com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol result = new com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fromId_ = fromId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.toId_ = toId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.chatType_ = chatType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.msgBody_ = msgBody_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.ext_ = ext_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol) {
          return mergeFrom((com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol other) {
        if (other == com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          bitField0_ |= 0x00000001;
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.hasFromId()) {
          setFromId(other.getFromId());
        }
        if (other.hasToId()) {
          setToId(other.getToId());
        }
        if (other.hasChatType()) {
          setChatType(other.getChatType());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasMsgBody()) {
          setMsgBody(other.getMsgBody());
        }
        if (other.hasExt()) {
          bitField0_ |= 0x00000100;
          ext_ = other.ext_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgId()) {
          return false;
        }
        if (!hasFromId()) {
          return false;
        }
        if (!hasToId()) {
          return false;
        }
        if (!hasChatType()) {
          return false;
        }
        if (!hasTimestamp()) {
          return false;
        }
        if (!hasLevel()) {
          return false;
        }
        if (!hasMsgType()) {
          return false;
        }
        if (!hasMsgBody()) {
          return false;
        }
        if (!hasExt()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object msgId_ = "";
      /**
       * <code>required string msgId = 1;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public String getMsgId() {
        Object ref = msgId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public Builder setMsgId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }

      private long fromId_ ;
      /**
       * <code>required int64 fromId = 2;</code>
       */
      public boolean hasFromId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 fromId = 2;</code>
       */
      public long getFromId() {
        return fromId_;
      }
      /**
       * <code>required int64 fromId = 2;</code>
       */
      public Builder setFromId(long value) {
        bitField0_ |= 0x00000002;
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 fromId = 2;</code>
       */
      public Builder clearFromId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fromId_ = 0L;
        onChanged();
        return this;
      }

      private long toId_ ;
      /**
       * <code>required int64 toId = 3;</code>
       */
      public boolean hasToId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 toId = 3;</code>
       */
      public long getToId() {
        return toId_;
      }
      /**
       * <code>required int64 toId = 3;</code>
       */
      public Builder setToId(long value) {
        bitField0_ |= 0x00000004;
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 toId = 3;</code>
       */
      public Builder clearToId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        toId_ = 0L;
        onChanged();
        return this;
      }

      private int chatType_ ;
      /**
       * <pre>
       * 聊天类型：单聊、群聊、语音通话
       * </pre>
       *
       * <code>required int32 chatType = 4;</code>
       */
      public boolean hasChatType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * 聊天类型：单聊、群聊、语音通话
       * </pre>
       *
       * <code>required int32 chatType = 4;</code>
       */
      public int getChatType() {
        return chatType_;
      }
      /**
       * <pre>
       * 聊天类型：单聊、群聊、语音通话
       * </pre>
       *
       * <code>required int32 chatType = 4;</code>
       */
      public Builder setChatType(int value) {
        bitField0_ |= 0x00000008;
        chatType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 聊天类型：单聊、群聊、语音通话
       * </pre>
       *
       * <code>required int32 chatType = 4;</code>
       */
      public Builder clearChatType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        chatType_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 5;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 timestamp = 5;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 5;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000010;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>required int32 level = 6;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 level = 6;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 6;</code>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000020;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 6;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000020);
        level_ = 0;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <pre>
       * 消息类型：文本、文件、图片等
       * </pre>
       *
       * <code>required int32 msgType = 7;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * 消息类型：文本、文件、图片等
       * </pre>
       *
       * <code>required int32 msgType = 7;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <pre>
       * 消息类型：文本、文件、图片等
       * </pre>
       *
       * <code>required int32 msgType = 7;</code>
       */
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000040;
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型：文本、文件、图片等
       * </pre>
       *
       * <code>required int32 msgType = 7;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msgBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes msgBody = 8;</code>
       */
      public boolean hasMsgBody() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required bytes msgBody = 8;</code>
       */
      public com.google.protobuf.ByteString getMsgBody() {
        return msgBody_;
      }
      /**
       * <code>required bytes msgBody = 8;</code>
       */
      public Builder setMsgBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        msgBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes msgBody = 8;</code>
       */
      public Builder clearMsgBody() {
        bitField0_ = (bitField0_ & ~0x00000080);
        msgBody_ = getDefaultInstance().getMsgBody();
        onChanged();
        return this;
      }

      private Object ext_ = "";
      /**
       * <pre>
       * 扩展
       * </pre>
       *
       * <code>required string ext = 9;</code>
       */
      public boolean hasExt() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <pre>
       * 扩展
       * </pre>
       *
       * <code>required string ext = 9;</code>
       */
      public String getExt() {
        Object ref = ext_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ext_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 扩展
       * </pre>
       *
       * <code>required string ext = 9;</code>
       */
      public com.google.protobuf.ByteString
          getExtBytes() {
        Object ref = ext_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ext_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 扩展
       * </pre>
       *
       * <code>required string ext = 9;</code>
       */
      public Builder setExt(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        ext_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 扩展
       * </pre>
       *
       * <code>required string ext = 9;</code>
       */
      public Builder clearExt() {
        bitField0_ = (bitField0_ & ~0x00000100);
        ext_ = getDefaultInstance().getExt();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 扩展
       * </pre>
       *
       * <code>required string ext = 9;</code>
       */
      public Builder setExtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        ext_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProtocol)
    }

    // @@protoc_insertion_point(class_scope:com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProtocol)
    private static final com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol();
    }

    public static com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<ChatMessageProtocol>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessageProtocol>() {
      public ChatMessageProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMessageProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMessageProtocol> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ChatMessageProtocol> getParserForType() {
      return PARSER;
    }

    public com.jjpicture.mvvmstar.im_common.protocol.ChatMessageProto.ChatMessageProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_star_common_protocol_ChatMessageProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_star_common_protocol_ChatMessageProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026ChatMessageProto.proto\022\030com.star.commo" +
      "n.protocol\"\245\001\n\023ChatMessageProtocol\022\r\n\005ms" +
      "gId\030\001 \002(\t\022\016\n\006fromId\030\002 \002(\003\022\014\n\004toId\030\003 \002(\003\022" +
      "\020\n\010chatType\030\004 \002(\005\022\021\n\ttimestamp\030\005 \002(\003\022\r\n\005" +
      "level\030\006 \002(\005\022\017\n\007msgType\030\007 \002(\005\022\017\n\007msgBody\030" +
      "\010 \002(\014\022\013\n\003ext\030\t \002(\tB\022B\020ChatMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_star_common_protocol_ChatMessageProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_star_common_protocol_ChatMessageProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_star_common_protocol_ChatMessageProtocol_descriptor,
        new String[] { "MsgId", "FromId", "ToId", "ChatType", "Timestamp", "Level", "MsgType", "MsgBody", "Ext", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
