// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogRequestProto.proto

package com.jjpicture.mvvmstar.im_common.protocol;

public final class LogRequestProto {
  private LogRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogRequestProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jjpicture.mvvmstar.im_common.protocol.LogRequestProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 from = 1;</code>
     */
    boolean hasFrom();
    /**
     * <code>required int64 from = 1;</code>
     */
    long getFrom();

    /**
     * <pre>
     * 0为登录 1为登出
     * </pre>
     *
     * <code>required int32 type = 2;</code>
     */
    boolean hasType();
    /**
     * <pre>
     * 0为登录 1为登出
     * </pre>
     *
     * <code>required int32 type = 2;</code>
     */
    int getType();

    /**
     * <code>required int64 timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code com.jjpicture.mvvmstar.im_common.protocol.LogRequestProtocol}
   */
  public  static final class LogRequestProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jjpicture.mvvmstar.im_common.protocol.LogRequestProtocol)
      LogRequestProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogRequestProtocol.newBuilder() to construct.
    private LogRequestProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogRequestProtocol() {
      from_ = 0L;
      type_ = 0;
      timestamp_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogRequestProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              from_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.internal_static_com_star_common_protocol_LogRequestProtocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.internal_static_com_star_common_protocol_LogRequestProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol.class, com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol.Builder.class);
    }

    private int bitField0_;
    public static final int FROM_FIELD_NUMBER = 1;
    private long from_;
    /**
     * <code>required int64 from = 1;</code>
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 from = 1;</code>
     */
    public long getFrom() {
      return from_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     * 0为登录 1为登出
     * </pre>
     *
     * <code>required int32 type = 2;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 0为登录 1为登出
     * </pre>
     *
     * <code>required int32 type = 2;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, from_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, from_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol)) {
        return super.equals(obj);
      }
      com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol other = (com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol) obj;

      boolean result = true;
      result = result && (hasFrom() == other.hasFrom());
      if (hasFrom()) {
        result = result && (getFrom()
            == other.getFrom());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && (getType()
            == other.getType());
      }
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFrom()) {
        hash = (37 * hash) + FROM_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFrom());
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jjpicture.mvvmstar.im_common.protocol.LogRequestProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jjpicture.mvvmstar.im_common.protocol.LogRequestProtocol)
        com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.internal_static_com_star_common_protocol_LogRequestProtocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.internal_static_com_star_common_protocol_LogRequestProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol.class, com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol.Builder.class);
      }

      // Construct using com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        from_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.internal_static_com_star_common_protocol_LogRequestProtocol_descriptor;
      }

      public com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol getDefaultInstanceForType() {
        return com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol.getDefaultInstance();
      }

      public com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol build() {
        com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol buildPartial() {
        com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol result = new com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol) {
          return mergeFrom((com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol other) {
        if (other == com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol.getDefaultInstance()) return this;
        if (other.hasFrom()) {
          setFrom(other.getFrom());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFrom()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        if (!hasTimestamp()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long from_ ;
      /**
       * <code>required int64 from = 1;</code>
       */
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 from = 1;</code>
       */
      public long getFrom() {
        return from_;
      }
      /**
       * <code>required int64 from = 1;</code>
       */
      public Builder setFrom(long value) {
        bitField0_ |= 0x00000001;
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 from = 1;</code>
       */
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = 0L;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * 0为登录 1为登出
       * </pre>
       *
       * <code>required int32 type = 2;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 0为登录 1为登出
       * </pre>
       *
       * <code>required int32 type = 2;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * 0为登录 1为登出
       * </pre>
       *
       * <code>required int32 type = 2;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 0为登录 1为登出
       * </pre>
       *
       * <code>required int32 type = 2;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jjpicture.mvvmstar.im_common.protocol.LogRequestProtocol)
    }

    // @@protoc_insertion_point(class_scope:com.jjpicture.mvvmstar.im_common.protocol.LogRequestProtocol)
    private static final com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol();
    }

    public static com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<LogRequestProtocol>
        PARSER = new com.google.protobuf.AbstractParser<LogRequestProtocol>() {
      public LogRequestProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogRequestProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogRequestProtocol> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LogRequestProtocol> getParserForType() {
      return PARSER;
    }

    public com.jjpicture.mvvmstar.im_common.protocol.LogRequestProto.LogRequestProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_star_common_protocol_LogRequestProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_star_common_protocol_LogRequestProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025LogRequestProto.proto\022\030com.jjpicture.mvvmstar.im_common" +
      ".protocol\"C\n\022LogRequestProtocol\022\014\n\004from\030" +
      "\001 \002(\003\022\014\n\004type\030\002 \002(\005\022\021\n\ttimestamp\030\003 \002(\003B\021" +
      "B\017LogRequestProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_star_common_protocol_LogRequestProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_star_common_protocol_LogRequestProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_star_common_protocol_LogRequestProtocol_descriptor,
        new String[] { "From", "Type", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
