// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageResponseProto.proto

package com.jjpicture.mvvmstar.im_common.protocol;

public final class MessageResponseProto {
  private MessageResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageResponseProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string msgId = 1;</code>
     */
    boolean hasMsgId();
    /**
     * <code>required string msgId = 1;</code>
     */
    String getMsgId();
    /**
     * <code>required string msgId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <code>required int64 timestamp = 2;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 2;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProtocol}
   */
  public  static final class MessageResponseProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProtocol)
      MessageResponseProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageResponseProtocol.newBuilder() to construct.
    private MessageResponseProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageResponseProtocol() {
      msgId_ = "";
      timestamp_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageResponseProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              msgId_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.internal_static_com_star_common_protocol_MessageResponseProtocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.internal_static_com_star_common_protocol_MessageResponseProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol.class, com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol.Builder.class);
    }

    private int bitField0_;
    public static final int MSGID_FIELD_NUMBER = 1;
    private volatile Object msgId_;
    /**
     * <code>required string msgId = 1;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string msgId = 1;</code>
     */
    public String getMsgId() {
      Object ref = msgId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msgId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 2;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol)) {
        return super.equals(obj);
      }
      com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol other = (com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol) obj;

      boolean result = true;
      result = result && (hasMsgId() == other.hasMsgId());
      if (hasMsgId()) {
        result = result && getMsgId()
            .equals(other.getMsgId());
      }
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgId()) {
        hash = (37 * hash) + MSGID_FIELD_NUMBER;
        hash = (53 * hash) + getMsgId().hashCode();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProtocol)
        com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.internal_static_com_star_common_protocol_MessageResponseProtocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.internal_static_com_star_common_protocol_MessageResponseProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol.class, com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol.Builder.class);
      }

      // Construct using com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.internal_static_com_star_common_protocol_MessageResponseProtocol_descriptor;
      }

      public com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol getDefaultInstanceForType() {
        return com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol.getDefaultInstance();
      }

      public com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol build() {
        com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol buildPartial() {
        com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol result = new com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol) {
          return mergeFrom((com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol other) {
        if (other == com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          bitField0_ |= 0x00000001;
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgId()) {
          return false;
        }
        if (!hasTimestamp()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object msgId_ = "";
      /**
       * <code>required string msgId = 1;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public String getMsgId() {
        Object ref = msgId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public Builder setMsgId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 2;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProtocol)
    }

    // @@protoc_insertion_point(class_scope:com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProtocol)
    private static final com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol();
    }

    public static com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<MessageResponseProtocol>
        PARSER = new com.google.protobuf.AbstractParser<MessageResponseProtocol>() {
      public MessageResponseProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageResponseProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageResponseProtocol> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessageResponseProtocol> getParserForType() {
      return PARSER;
    }

    public com.jjpicture.mvvmstar.im_common.protocol.MessageResponseProto.MessageResponseProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_star_common_protocol_MessageResponseProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_star_common_protocol_MessageResponseProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032MessageResponseProto.proto\022\030com.star.c" +
      "ommon.protocol\";\n\027MessageResponseProtoco" +
      "l\022\r\n\005msgId\030\001 \002(\t\022\021\n\ttimestamp\030\002 \002(\003B\026B\024M" +
      "essageResponseProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_star_common_protocol_MessageResponseProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_star_common_protocol_MessageResponseProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_star_common_protocol_MessageResponseProtocol_descriptor,
        new String[] { "MsgId", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
