// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SDPMessageProto.proto

package com.jjpicture.mvvmstar.im_common.protocol;

public final class SDPMessageProto {
  private SDPMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SDPMessageProtocolOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProtocol)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 msgType = 1;</code>
     */
    boolean hasMsgType();
    /**
     * <code>required int32 msgType = 1;</code>
     */
    int getMsgType();

    /**
     * <code>required int64 fromId = 2;</code>
     */
    boolean hasFromId();
    /**
     * <code>required int64 fromId = 2;</code>
     */
    long getFromId();

    /**
     * <code>required int64 toId = 3;</code>
     */
    boolean hasToId();
    /**
     * <code>required int64 toId = 3;</code>
     */
    long getToId();

    /**
     * <code>required string sdp = 4;</code>
     */
    boolean hasSdp();
    /**
     * <code>required string sdp = 4;</code>
     */
    String getSdp();
    /**
     * <code>required string sdp = 4;</code>
     */
    com.google.protobuf.ByteString
        getSdpBytes();

    /**
     * <code>required string sdpType = 5;</code>
     */
    boolean hasSdpType();
    /**
     * <code>required string sdpType = 5;</code>
     */
    String getSdpType();
    /**
     * <code>required string sdpType = 5;</code>
     */
    com.google.protobuf.ByteString
        getSdpTypeBytes();

    /**
     * <code>required int64 timestamp = 6;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 6;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProtocol}
   */
  public  static final class SDPMessageProtocol extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProtocol)
      SDPMessageProtocolOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SDPMessageProtocol.newBuilder() to construct.
    private SDPMessageProtocol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SDPMessageProtocol() {
      msgType_ = 0;
      fromId_ = 0L;
      toId_ = 0L;
      sdp_ = "";
      sdpType_ = "";
      timestamp_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SDPMessageProtocol(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fromId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              toId_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              sdp_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              sdpType_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.internal_static_com_star_common_protocol_SDPMessageProtocol_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.internal_static_com_star_common_protocol_SDPMessageProtocol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol.class, com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol.Builder.class);
    }

    private int bitField0_;
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <code>required int32 msgType = 1;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 msgType = 1;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int FROMID_FIELD_NUMBER = 2;
    private long fromId_;
    /**
     * <code>required int64 fromId = 2;</code>
     */
    public boolean hasFromId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 fromId = 2;</code>
     */
    public long getFromId() {
      return fromId_;
    }

    public static final int TOID_FIELD_NUMBER = 3;
    private long toId_;
    /**
     * <code>required int64 toId = 3;</code>
     */
    public boolean hasToId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 toId = 3;</code>
     */
    public long getToId() {
      return toId_;
    }

    public static final int SDP_FIELD_NUMBER = 4;
    private volatile Object sdp_;
    /**
     * <code>required string sdp = 4;</code>
     */
    public boolean hasSdp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string sdp = 4;</code>
     */
    public String getSdp() {
      Object ref = sdp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sdp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sdp = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSdpBytes() {
      Object ref = sdp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sdp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SDPTYPE_FIELD_NUMBER = 5;
    private volatile Object sdpType_;
    /**
     * <code>required string sdpType = 5;</code>
     */
    public boolean hasSdpType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string sdpType = 5;</code>
     */
    public String getSdpType() {
      Object ref = sdpType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sdpType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sdpType = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSdpTypeBytes() {
      Object ref = sdpType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sdpType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 6;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 timestamp = 6;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasToId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSdp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSdpType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, fromId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, toId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sdp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, sdpType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, fromId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, toId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sdp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, sdpType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol)) {
        return super.equals(obj);
      }
      com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol other = (com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol) obj;

      boolean result = true;
      result = result && (hasMsgType() == other.hasMsgType());
      if (hasMsgType()) {
        result = result && (getMsgType()
            == other.getMsgType());
      }
      result = result && (hasFromId() == other.hasFromId());
      if (hasFromId()) {
        result = result && (getFromId()
            == other.getFromId());
      }
      result = result && (hasToId() == other.hasToId());
      if (hasToId()) {
        result = result && (getToId()
            == other.getToId());
      }
      result = result && (hasSdp() == other.hasSdp());
      if (hasSdp()) {
        result = result && getSdp()
            .equals(other.getSdp());
      }
      result = result && (hasSdpType() == other.hasSdpType());
      if (hasSdpType()) {
        result = result && getSdpType()
            .equals(other.getSdpType());
      }
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && (getTimestamp()
            == other.getTimestamp());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMsgType()) {
        hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMsgType();
      }
      if (hasFromId()) {
        hash = (37 * hash) + FROMID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFromId());
      }
      if (hasToId()) {
        hash = (37 * hash) + TOID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getToId());
      }
      if (hasSdp()) {
        hash = (37 * hash) + SDP_FIELD_NUMBER;
        hash = (53 * hash) + getSdp().hashCode();
      }
      if (hasSdpType()) {
        hash = (37 * hash) + SDPTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getSdpType().hashCode();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProtocol}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProtocol)
        com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.internal_static_com_star_common_protocol_SDPMessageProtocol_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.internal_static_com_star_common_protocol_SDPMessageProtocol_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol.class, com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol.Builder.class);
      }

      // Construct using com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        fromId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        toId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        sdp_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sdpType_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.internal_static_com_star_common_protocol_SDPMessageProtocol_descriptor;
      }

      public com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol getDefaultInstanceForType() {
        return com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol.getDefaultInstance();
      }

      public com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol build() {
        com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol buildPartial() {
        com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol result = new com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fromId_ = fromId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.toId_ = toId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sdp_ = sdp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sdpType_ = sdpType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol) {
          return mergeFrom((com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol other) {
        if (other == com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol.getDefaultInstance()) return this;
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasFromId()) {
          setFromId(other.getFromId());
        }
        if (other.hasToId()) {
          setToId(other.getToId());
        }
        if (other.hasSdp()) {
          bitField0_ |= 0x00000008;
          sdp_ = other.sdp_;
          onChanged();
        }
        if (other.hasSdpType()) {
          bitField0_ |= 0x00000010;
          sdpType_ = other.sdpType_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgType()) {
          return false;
        }
        if (!hasFromId()) {
          return false;
        }
        if (!hasToId()) {
          return false;
        }
        if (!hasSdp()) {
          return false;
        }
        if (!hasSdpType()) {
          return false;
        }
        if (!hasTimestamp()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgType_ ;
      /**
       * <code>required int32 msgType = 1;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 msgType = 1;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>required int32 msgType = 1;</code>
       */
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000001;
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 msgType = 1;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private long fromId_ ;
      /**
       * <code>required int64 fromId = 2;</code>
       */
      public boolean hasFromId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 fromId = 2;</code>
       */
      public long getFromId() {
        return fromId_;
      }
      /**
       * <code>required int64 fromId = 2;</code>
       */
      public Builder setFromId(long value) {
        bitField0_ |= 0x00000002;
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 fromId = 2;</code>
       */
      public Builder clearFromId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fromId_ = 0L;
        onChanged();
        return this;
      }

      private long toId_ ;
      /**
       * <code>required int64 toId = 3;</code>
       */
      public boolean hasToId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 toId = 3;</code>
       */
      public long getToId() {
        return toId_;
      }
      /**
       * <code>required int64 toId = 3;</code>
       */
      public Builder setToId(long value) {
        bitField0_ |= 0x00000004;
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 toId = 3;</code>
       */
      public Builder clearToId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        toId_ = 0L;
        onChanged();
        return this;
      }

      private Object sdp_ = "";
      /**
       * <code>required string sdp = 4;</code>
       */
      public boolean hasSdp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string sdp = 4;</code>
       */
      public String getSdp() {
        Object ref = sdp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sdp_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string sdp = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSdpBytes() {
        Object ref = sdp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sdp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sdp = 4;</code>
       */
      public Builder setSdp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sdp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sdp = 4;</code>
       */
      public Builder clearSdp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sdp_ = getDefaultInstance().getSdp();
        onChanged();
        return this;
      }
      /**
       * <code>required string sdp = 4;</code>
       */
      public Builder setSdpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sdp_ = value;
        onChanged();
        return this;
      }

      private Object sdpType_ = "";
      /**
       * <code>required string sdpType = 5;</code>
       */
      public boolean hasSdpType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string sdpType = 5;</code>
       */
      public String getSdpType() {
        Object ref = sdpType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sdpType_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string sdpType = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSdpTypeBytes() {
        Object ref = sdpType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sdpType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sdpType = 5;</code>
       */
      public Builder setSdpType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sdpType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sdpType = 5;</code>
       */
      public Builder clearSdpType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sdpType_ = getDefaultInstance().getSdpType();
        onChanged();
        return this;
      }
      /**
       * <code>required string sdpType = 5;</code>
       */
      public Builder setSdpTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sdpType_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 6;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 timestamp = 6;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 6;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000020;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 6;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProtocol)
    }

    // @@protoc_insertion_point(class_scope:com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProtocol)
    private static final com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol();
    }

    public static com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<SDPMessageProtocol>
        PARSER = new com.google.protobuf.AbstractParser<SDPMessageProtocol>() {
      public SDPMessageProtocol parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SDPMessageProtocol(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SDPMessageProtocol> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SDPMessageProtocol> getParserForType() {
      return PARSER;
    }

    public com.jjpicture.mvvmstar.im_common.protocol.SDPMessageProto.SDPMessageProtocol getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_star_common_protocol_SDPMessageProtocol_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_star_common_protocol_SDPMessageProtocol_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025SDPMessageProto.proto\022\030com.jjpicture.mvvmstar.im_common" +
      ".protocol\"t\n\022SDPMessageProtocol\022\017\n\007msgTy" +
      "pe\030\001 \002(\005\022\016\n\006fromId\030\002 \002(\003\022\014\n\004toId\030\003 \002(\003\022\013" +
      "\n\003sdp\030\004 \002(\t\022\017\n\007sdpType\030\005 \002(\t\022\021\n\ttimestam" +
      "p\030\006 \002(\003B\021B\017SDPMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_star_common_protocol_SDPMessageProtocol_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_star_common_protocol_SDPMessageProtocol_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_star_common_protocol_SDPMessageProtocol_descriptor,
        new String[] { "MsgType", "FromId", "ToId", "Sdp", "SdpType", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
